spring:
  application:
    name: tourfolio
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:tourfoliodb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

server:
  port: ${SERVER_PORT:8000}

swagger:
  server-url: ${SWAGGER_SERVER_URL:http://localhost:8000}

openapi:
  service:
    key: ${OPENAPI_SERVICE_KEY:}

endpoint:
  demand: ${ENDPOINT_DEMAND:https://apis.data.go.kr/B551011/AreaTarDemDsService}
  resdem: ${ENDPOINT_RESDEM:https://apis.data.go.kr/B551011/AreaTarResDemService}
  visitor: ${ENDPOINT_VISITOR:https://apis.data.go.kr/B551011/DataLabService}
  forecast: ${ENDPOINT_FORECAST:https://apis.data.go.kr/B551011/TatsCnctrRateService}

logging:
  level:
    root: INFO
    com.tourfolio.app: DEBUG   # 디버깅을 위해 DEBUG 레벨로 상향
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # SQL 파라미터 확인용
