spring.application.name=tourfolio
server.port=8000

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.force=true

spring.datasource.url=jdbc:h2:mem:tourfoliodb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

openapi.service.key=9gW0r4tl6Md49Aj9LDANE3in2AU8Flq7n+R/4GTTeYn5lukUig9L8VpQprv+3XNhbLJmtGkOYtydXle35DQG8A==
# 관광 수요 강도 지표 API
endpoint.demand=https://apis.data.go.kr/B551011/AreaTarDemDsService
# 관광 자원 수요 지표 API
endpoint.resdem=https://apis.data.go.kr/B551011/AreaTarResDemService
# 방문자 추이 지표 API
endpoint.visitor=https://apis.data.go.kr/B551011/DataLabService
# 집중률 예측 지표 API
endpoint.forecast=https://apis.data.go.kr/B551011/TatsCnctrRateService
