spring:
  application:
    name: tourfolio

  datasource:
    url: jdbc:mysql://tourfolio-db.cojqgcqou7q8.us-east-1.rds.amazonaws.com:3306/tourfolio?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: tourfolio1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8000
  # Reverse Proxy (Nginx) 사용 시 HTTPS 헤더 인식을 위한 설정
  forward-headers-strategy: framework

swagger:
  # Swagger UI 기본 요청 서버 URL (운영 도메인)
  server-url: https://tourfolio.kr

tour:
  api:
    # URL 인코딩된 키
    service-key: ${TOUR_API_SERVICE_KEY:9gW0r4tl6Md49Aj9LDANE3in2AU8Flq7n%2BR%2F4GTTeYn5lukUig9L8VpQprv%2B3XNhbLJmtGkOYtydXle35DQG8A%3D%3D}
    base-url: https://apis.data.go.kr

kakao:
  client-id: ${KAKAO_CLIENT_ID:}
  redirect-uri: https://tourfolio.kr/api/v1/auth/kakao/callback

logging:
  level:
    com.tourfolio.app: DEBUG
    org.hibernate.SQL: DEBUG
